-- MySQL Script generated by MySQL Workbench
-- Sat Sep 16 12:37:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `booking` ;

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booking` ;
USE `booking` ;

-- -----------------------------------------------------
-- Table `booking`.`amenity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking`.`amenity` ;

CREATE TABLE IF NOT EXISTS `booking`.`amenity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking`.`user` ;

CREATE TABLE IF NOT EXISTS `booking`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `password` CHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ak_email` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking`.`reservation` ;

CREATE TABLE IF NOT EXISTS `booking`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` INT NOT NULL,
  `end_time` INT NOT NULL,
  `date` INT NOT NULL,
  `amenity_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_amenity_idx` (`amenity_id` ASC),
  INDEX `fk_reservation_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_reservation_amenity`
    FOREIGN KEY (`amenity_id`)
    REFERENCES `booking`.`amenity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservation_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `booking`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `booking`.`amenity`
-- -----------------------------------------------------
START TRANSACTION;
USE `booking`;
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (1, 'Mitel Networks Corporation');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (2, 'Navios Maritime Partners LP');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (3, 'Coherent');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (4, 'AmTrust Financial Services');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (5, 'Tetra Technologies');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (6, 'Advanced Drainage Systems');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (7, 'Caesars Entertainment Corporation');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (8, 'First Trust International Multi-Asset Diversified Income Index');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (9, 'Mylan N.V.');
INSERT INTO `booking`.`amenity` (`id`, `name`) VALUES (10, 'Blackrock Municipal Income Quality Trust');

COMMIT;

